---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora-demo-vm-hot-plug-disk
  namespace: koray
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: false
    kind: VirtualMachine
    name: fedora-demo-vm
    uid: 9be84bc9-08d6-4bf9-a210-86a973811f6f
spec:
  storage:
    resources:
      requests:
        storage: 10Gi
    storageClassName: ocs-storagecluster-ceph-rbd-replica2
  preallocation: false
  source:
    blank: {}
